class AppLocalizations {
  static const Map<String, Map<String, String>> _localizedStrings = {
    'en': {
      'hello_admin': 'Hello Admin 👋',
      'system_control_panel': 'System Control Panel',
      'system_status': 'System Status: Active',
      'management_tools': 'Management Tools',
      'users_management': 'Users\nManagement',
      'view_reports': 'View\nReports',
      'system_analytics': 'System\nAnalytics',
      'verify_products': 'Verify\nProducts',
      'market_control': 'Market\nControl',
      'blockchain_logs': 'Blockchain\nLogs',
      'system_notices': 'System Notices',
      'pending_verification': '3 pending product verification requests',
      'server_running': 'Server running smoothly',
      'new_registrations': 'New user registrations this week: 42',
      'hello_farmer': 'Hello, Farmer 👋',
      'ceylon_pepper': 'Ceylon Pepper',
      'fetching_location': 'Fetching location...',
      'tap_to_refresh': 'Tap to refresh',
      'total_crops': 'Total Plots',
      'active_alerts': 'Active Alerts',
      'avg_quality': 'Avg Quality',
      'smart_farming_tools': 'Smart Farming Tools',
      'yield_prediction': 'Yield\nPrediction',
      'forecast_harvest': 'Forecast harvest',
      'disease_detection': 'Disease\nDetection',
      'ai_diagnosis': 'AI diagnosis',
      'quality_grading': 'Quality\nGrading',
      'grade_your_harvest': 'Grade Your Harvest',
      'market_forecast': 'Market\nForecast',
      'price_trends': 'Price trends',
      'more_services': 'More Services',
      'ai_assistant': 'AI Assistant',
      'explore': 'Explore',
      'marketplace': 'Marketplace',
      'farming_tips_insights': 'Farming Tips & Insights',
      'monitor_soil_moisture': 'Monitor soil moisture regularly',
      'apply_organic_fertilizers': 'Apply organic fertilizers monthly',
      'check_pest_damage': 'Check for pest damage daily',
      'maintain_plant_spacing': 'Maintain proper plant spacing',
      'harvest_optimal_maturity': 'Harvest at optimal maturity',
      'profile': 'Profile',
      'settings': 'Settings',
      'logout': 'Logout',
      // Disease detection screen keys
      'hello_user': 'Hello, {name} 👋',
      'disease_detection_title': 'Disease Detection',
      'disease_description':
          'Access AI-powered disease detection, community posts, and complaint management all in one place.',
      'explore_features': 'Explore Features',
      'view_posts': 'View Posts',
      'view_posts_subtitle': 'Create and view social posts',
      'make_complaint': 'Make a Complaint',
      'make_complaint_subtitle': 'Submit your complaints or issues',
      'manage_complaints': 'Manage Complaints',
      'manage_complaints_subtitle': 'View and manage all complaints',
      'analyze_plants': 'Analyze Plants',
      'analyze_plants_subtitle': 'Detect plant diseases with AI',
      'detection_camera': 'Disease Detection Camera',
      'detection_camera_subtitle': 'Scan disease photos using camera',
      'photo_captured': 'Photo captured!',
      // Disease result screen keys
      'disease_detection_result': 'Disease Detection Result',
      'analyzing_image': 'Analyzing Image...',
      'using_cnn_model': 'Using CNN Model for disease detection',
      'detection_failed': 'Detection Failed',
      'retry': 'Retry',
      'confidence_level': 'Confidence Level',
      'model_confidence': 'Model confidence in disease prediction',
      'description': 'Description',
      'treatment': 'Treatment',
      'prevention': 'Prevention',
      'all_predictions': 'All Predictions',
      'analyze_another_image': 'Analyze Another Image',
      'go_back': 'Go Back',
      // Image picker screen keys
      'add_photo': 'Add Photo',
      'choose_photo_source': 'Choose Photo Source',
      'select_how_you_want_to_add_photo':
          'Select how you want to add your photo',
      'take_photo': 'Take Photo',
      'take_photo_with_camera': 'Take a photo using your camera',
      'pick_from_gallery': 'Pick from Gallery',
      'select_existing_photo': 'Select an existing photo',
      // Weather forecast screen keys
      'weather_forecast_title': 'Weather Forecast',
      'weather_forecast': 'Weather\nForecast',
      'weather_forecast_subtitle': 'Check weather & conditions',
      'loading_weather': 'Loading weather data...',
      'weather_error': 'Unable to load weather data. Please try again.',
      'current_conditions': 'Current Conditions',
      'humidity': 'Humidity',
      'temperature': 'Temperature',
      'rainfall': 'Rainfall',
      'last_updated': 'Last updated',
      'weather_alerts': 'Weather Alerts & Notifications',
      'all_conditions_normal': 'All weather conditions are normal. Keep monitoring!',
      'past_7_days': 'Past 7 Days Overview',
      'search_location': 'Search Location',
      'enter_city_name': 'Enter city name',
      'use_current_location': 'Use current location',
      'search': 'Search',
      'cancel': 'Cancel',
    },
    'si': {
      'hello_admin': 'ආයුබෝවන් පරිපාලක 👋',
      'system_control_panel': 'පද්ධති පාලන පුවරුව',
      'system_status': 'පද්ධති තත්ත්වය: සක්‍රිය',
      'management_tools': 'කළමනාකරණ මෙවලම්',
      'users_management': 'පරිශීලක\nකළමනාකරණ',
      'view_reports': 'වාර්තා\nපෙන්වන්න',
      'system_analytics': 'පද්ධති\nවිශ්ලේෂණ',
      'verify_products': 'නිෂ්පාදන\nසත්යාපනය',
      'market_control': 'වෙළඳ පොළ\nපාලනය',
      'blockchain_logs': 'බ්ලොක්චේන්\nලඝු-සටහන්',
      'system_notices': 'පද්ධති සිංහ දර්ශන',
      'pending_verification': 'නිෂ්පාදන සත්යාපනයට අපේක්ෂිත ඉල්ලීම් 3ක්',
      'server_running': 'සේවාදායක සුමට ව්‍යවහාරයෙන් ක්‍රියාත්මක වේ',
      'new_registrations': 'මෙම සතියේ නව පරිශීලක ලියාපදිංචි කිරීම්: 42',
      'hello_farmer': 'ආයුබෝවන්, ගොවිතුරු 👋',
      'ceylon_pepper': 'සිලෝන් තුරුස්',
      'fetching_location': 'පිහිටීම් සොයා ගනිමින්...',
      'tap_to_refresh': 'යළි ලබා ගැනීමට තට්ටු කරන්න',
      'total_crops': 'මුළු බෝග',
      'active_alerts': 'සක්‍රිය ඉවුවා',
      'avg_quality': 'සාමාන්‍ය තත්ව',
      'smart_farming_tools': 'බුද්ධිමත් ගොවිතැනීමේ මෙවලම්',
      'yield_prediction': 'අස්වැන්න\nඅනාවැකි',
      'forecast_harvest': 'කාලගුණ අනාවැකි',
      'disease_detection': 'රෝග\nඉවුවාකරණ',
      'ai_diagnosis': 'AI විනිශ්චයය',
      'quality_grading': 'ගුණොත්තරය\nශ්‍රේණිගත කිරීම',
      'iso_standards': 'ISO ප්‍රමිති',
      'market_forecast': 'වෙළඳ පොළ\nපුර්‍වබස්‍ස',
      'price_trends': 'මිල ප්‍රවණතා',
      'more_services': 'තවත් සේවා',
      'ai_assistant': 'AI සහායකයා',
      'explore': 'ගවේෂණ කරන්න',
      'marketplace': 'වෙළඳ පිටිය',
      'farming_tips_insights': 'ගොවිතැටීමේ ඉඟි සහ අවබෝධයන්',
      'monitor_soil_moisture': 'මතුර්වත්තාවේ ආර්ද්‍රතා නිතිපතා නිරීක්ෂණ කරන්න',
      'apply_organic_fertilizers': 'ඔටුන් පුෂ්පදුර මාසිකව යොදන්න',
      'check_pest_damage': 'දිනපතා කීටක හානිය පරීක්ෂා කරන්න',
      'maintain_plant_spacing': 'ඩිම පැල අවකාශ පවත්වා ගන්න',
      'harvest_optimal_maturity': 'සුදුසු පරිණතකාලයේ අස්වැන්න ගන්න',
      'profile': 'ප්‍රොශයිල්',
      'settings': 'සැකසුම්',
      'logout': 'ඉවත් කරන්න',
      // Disease detection keys
      'hello_user': 'ආයුබෝවන්, ගොවි මහතා 👋',
      'disease_detection_title': 'රෝග හඳුනාගැනීම',
      'disease_description':
          'AI පදනම්වූ රෝග හඳුනාගැනීම්, පැමිණිලි හා කළමනාකරණ සේවාවන් එකට ලැබෙන තැන.',
      'explore_features': 'විශේෂාංග පරීක්ෂා කරන්න',
      'view_posts': 'පෝස්ට් බලන්න',
      'view_posts_subtitle': 'පෝස්ට් නිර්මාණය සහ බැලීම',
      'make_complaint': 'පැමිණිලි කරන්න',
      'make_complaint_subtitle': 'ඔබගේ පැමිණිලි හෝ ගැටළු ඉදිරිපත් කරන්න',
      'manage_complaints': 'පැමිණිලි කළමනාකරණය',
      'manage_complaints_subtitle': 'සියලු පැමිණිලි නැරඹීම සහ කළමනාකරණය',
      'analyze_plants': 'පැල විශ්ලේෂණය',
      'analyze_plants_subtitle': 'AI සමඟ පැල රෝග හඳුනාගැනීම',
      'detection_camera': 'රෝග හඳුනාගැනීම කැමරා',
      'detection_camera_subtitle': 'කැමරා භාවිතයෙන් රෝග ඡායාරූප ස්කෑන් කරන්න',
      'photo_captured': 'ඡායාරූපය ගන්නා ලදී!',
      // Disease result screen keys
      'disease_detection_result': 'රෝග හඳුනාගැනීම ප්‍රතිඵල',
      'analyzing_image': 'ඡායාරූපය විශ්ලේෂණය කරමින්...',
      'using_cnn_model': 'CNN ආකෘතිය භාවිතයෙන් රෝග හඳුනාගැනීම',
      'detection_failed': 'හඳුනාගැනීම අසාර්තකයි',
      'retry': 'නැවත උත්සාහ කරන්න',
      'confidence_level': 'විශ්වාස මට්ටම',
      'model_confidence': 'මොඩලයේ විශ්වාසවන්තභාවය',
      'description': 'විස්තරණය',
      'treatment': 'ප්‍රතිකාර',
      'prevention': 'වැළැක්කම',
      'all_predictions': 'සියලු පුරෝකතන',
      'analyze_another_image': 'තවත් ඡායාරූපයක් විශ්ලේෂණය කරන්න',
      'go_back': 'ආපසු යන්න',
      // Image picker screen keys
      'add_photo': 'ඡායාරූපය එකතු කරන්න',
      'choose_photo_source': 'ඡායාරූප නිධිය තෝරන්න',
      'select_how_you_want_to_add_photo':
          'ඡායාරූපයක් එකතු කිරීමට ඇති ආකාර තෝරන්න',
      'take_photo': 'ඡායාරූපයක් ගන්න',
      'take_photo_with_camera': 'ඔබගේ කැමරාව භාවිතයෙන් ඡායාරූපයක් ගන්න',
      'pick_from_gallery': 'ගැලරිය සිට තෝරන්න',
      'select_existing_photo': 'පවතින ඡායාරූපයක් තෝරන්න',
      // Weather forecast screen keys
      'weather_forecast_title': 'කාලගුණ පුර්‍වබස්‍ස',
      'weather_forecast': 'කාලගුණ\nපුර්‍වබස්‍ස',
      'weather_forecast_subtitle': 'කාලගුණ පරීක්ෂා කරන්න',
      'loading_weather': 'කාලගුණ තොරතුරු පූරණය කරමින්...',
      'weather_error': 'කාලගුණ තොරතුරු පූරණය කළ නොහැක. නැවත උත්සාහ කරන්න.',
      'current_conditions': 'වර්තමාන තත්ත්වයන්',
      'humidity': 'ආර්ද්‍රතා',
      'temperature': 'උෂ්ණත්වය',
      'rainfall': 'වර්ෂාපතනය',
      'last_updated': 'අවසාන වරට යාවත්කාලීනයි',
      'weather_alerts': 'කාලගුණ ඉවුවා සහ දැනුම්දීම්',
      'all_conditions_normal': 'සියලු කාලගුණ තත්ත්වයන් සාමාන්‍ය ය. නිරීක්ෂණ කරගෙන යන්න!',
      'past_7_days': 'පසුගිය දින 7 හි දළ විශ්ලේෂණය',
      'search_location': 'පිහිටීම සොයන්න',
      'enter_city_name': 'නගරයේ නම ඇතුළු කරන්න',
      'use_current_location': 'වර්තමාන පිහිටීම භාවිතා කරන්න',
      'search': 'සොයන්න',
      'cancel': 'අවලංගු කරන්න',
    },
    'ta': {
      'hello_admin': 'வணக்கம் நிர்வாகி 👋',
      'system_control_panel': 'கணினி கட்டுப்பாட்டு பலகை',
      'system_status': 'கணினி நிலை: செயல்படுகிறது',
      'management_tools': 'நிர்வாகக் கருவிகள்',
      'users_management': 'பயனர்\nநிர்வாகம்',
      'view_reports': 'அறிக்கைகளை\nபார்க்க',
      'system_analytics': 'கணினி\nவிश்லேஷணம்',
      'verify_products': 'பொருட்களை\nச்சரிபார்க்க',
      'market_control': 'சந்தை\nகட்டுப்பாடு',
      'blockchain_logs': 'சங்கிலி\nலாग்கள்',
      'system_notices': 'கணினி அறிவிப்புகள்',
      'pending_verification':
          '3 பொருள் சரிபார்ப்பு கோரிக்கைகள் நிலுவையில் உள்ளன',
      'server_running': 'சேவையகம் சிறப்பாக இயங்குகிறது',
      'new_registrations': 'இந்த வாரத்தில் புதிய பயனர் பதிவுகள்: 42',
      'hello_farmer': 'வணக்கம், விவசாயி 👋',
      'ceylon_pepper': 'சிலோன் மிளகு',
      'fetching_location': 'இடத்தைப் பெறுகிறது...',
      'tap_to_refresh': 'புதுப்பிக்க தட்டவும்',
      'total_crops': 'மொத்த பயிர்கள்',
      'active_alerts': 'செயல்படும் எச்சரிக்கைகள்',
      'avg_quality': 'சராசரி தரம்',
      'smart_farming_tools': 'நுணுக்கமான விவசாய கருவிகள்',
      'yield_prediction': 'விளைச்சல்\nகணிப்பு',
      'forecast_harvest': 'விளைச்சல் முன்னறிவிப்பு',
      'disease_detection': 'நோய்\nகண்டறிதல்',
      'ai_diagnosis': 'AI நிர்ணயம்',
      'quality_grading': 'தரம்\nவகைப்படுத்தல்',
      'iso_standards': 'ISO தரநிலைகள்',
      'market_forecast': 'சந்தை\nகணிப்பு',
      'price_trends': 'விலை போக்குகள்',
      'more_services': 'மேலும் சேவைகள்',
      'ai_assistant': 'AI உதவியாளர்',
      'explore': 'ஆராயுங்கள்',
      'marketplace': 'சந்தைப்படம்',
      'farming_tips_insights': 'விவசாய குறிப்புகள் & அன்தர்ஞானம்',
      'monitor_soil_moisture': 'மண் ஈரப்பதத்தை தொடர்ந்து கண்காணிக்கவும்',
      'apply_organic_fertilizers': 'மாதிக எரு பயன்படுத்தவும்',
      'check_pest_damage': 'தினசரி பூச்சி சேதத்தை சரிபார்க்கவும்',
      'maintain_plant_spacing': 'சரியான தாவர间격 பராமரிக்கவும்',
      'harvest_optimal_maturity': 'உகந்த முதிர்ச்சிதேன் விளைச்சல் அறுக்கவும்',
      'profile': 'சுயவிவரம்',
      'settings': 'அமைப்புகள்',
      'logout': 'வெளியேறவும்',
      // Disease detection keys
      'hello_user': 'வணக்கம், {name} 👋',
      'disease_detection_title': 'நோய் கண்டறிதல்',
      'disease_description':
          'AI இயக்கும் நோய் கண்டறிதல்கள், சமூக இடுகைகள் மற்றும் புகார் மேலாண்மை ஒரே இடத்தில்.',
      'explore_features': 'செயல்பாடுகளை ஆராயுங்கள்',
      'view_posts': 'பதிவுகளை காண்க',
      'view_posts_subtitle': 'சமூக பதிவுகளை உருவாக்கவும் காணவும்',
      'make_complaint': 'ஒரு புகார் பதிவேற்றம்',
      'make_complaint_subtitle':
          'உங்கள் புகார்கள் அல்லது பிரச்சினைகளை சமர்ப்பிக்கவும்',
      'manage_complaints': 'புகார்கள் நிர்வாகம்',
      'manage_complaints_subtitle':
          'அனைத்து புகார்கள் காணவும் மற்றும் நிர்வகிக்கவும்',
      'analyze_plants': 'பயிர்களை பகுப்பாய்வு',
      'analyze_plants_subtitle': 'AI உடன் பயிர் நோய்களை கண்டறிக',
      'detection_camera': 'நோய் கண்டறிதல் கேமரா',
      'detection_camera_subtitle': 'காமெராவினால் நோய் படங்களை ஸ்கேன் செய்யவும்',
      'photo_captured': 'படம் பதிவு செய்யப்பட்டது!',
      // Disease result screen keys
      'disease_detection_result': 'நோய் கண்டறிதல் முடிவு',
      'analyzing_image': 'படத்தை பகுப்பாய்வு செய்கிறது...',
      'using_cnn_model': 'CNN மாதிரியைப் பயன்படுத்தி நோய் கண்டறிதல்',
      'detection_failed': 'கண்டறிதல் தோல்வியடைந்தது',
      'retry': 'மீண்டும் முயற்சி செய்க',
      'confidence_level': 'நம்பிக்கை நிலை',
      'model_confidence': 'நோய் கணிப்பில் மாதிரியின் நம்பிக்கை',
      'description': 'விளக்கம்',
      'treatment': 'சிகிச்சை',
      'prevention': 'தடுப்பு',
      'all_predictions': 'அனைத்து கணிப்புகள்',
      'analyze_another_image': 'மற்றொரு படத்தை பகுப்பாய்வு செய்க',
      'go_back': 'திரும்பிச் செல்க',
      // Image picker screen keys
      'add_photo': 'படம் சேர்க்க',
      'choose_photo_source': 'ஃபோட்டோ மூலத்தைத் தேர்ந்தெடுக்கவும்',
      'select_how_you_want_to_add_photo':
          'நீங்கள் ஃபோட்டோவை எவ்வாறு சேர்க்க விரும்புகிறீர்கள் என்பதைத் தேர்ந்தெடுக்கவும்',
      'take_photo': 'ஃபோட்டோ எடுக்க',
      'take_photo_with_camera':
          'உங்கள் கேமராவைப் பயன்படுத்தி ஒரு ஃபோட்டோ எடுக்கவும்',
      'pick_from_gallery': 'கேலரியிலிருந்து தேர்ந்தெடுக்க',
      'select_existing_photo': 'ஒரு பிற்பাதகொண்ட ஃபோட்டோவைத் தேர்ந்தெடுக்கவும்',
      // Weather forecast screen keys
      'weather_forecast_title': 'காலநிலை கணிப்பு',
      'weather_forecast': 'காலநிலை\nகணிப்பு',
      'weather_forecast_subtitle': 'காலநிலை மற்றும் நிலைமை சரிபார்க்கவும்',
      'loading_weather': 'காலநிலை தரவை பூரணப்படுத்துகிறது...',
      'weather_error': 'காலநிலை தரவை பூரணப்படுத்த முடியவில்லை. மீண்டும் முயற்சி செய்க.',
      'current_conditions': 'தற்போதைய நிலைமைகள்',
      'humidity': 'ஈரப்பதம்',
      'temperature': 'வெப்பநிலை',
      'rainfall': 'மழைப்பொழிவு',
      'last_updated': 'கடைசியாக புதுப்பிக்கப்பட்டது',
      'weather_alerts': 'காலநிலை எச்சரிக்கைகள் மற்றும் அறிவிப்புகள்',
      'all_conditions_normal': 'அனைத்து காலநிலை நிலைமைகளும் சாதாரணமாக உள்ளன. கண்காணிக்க வேண்டும்!',
      'past_7_days': 'கடந்த 7 நாட்களின் மேலோட்டம்',
      'search_location': 'இடத்தைத் தேடுங்கள்',
      'enter_city_name': 'நகரத்தின் பெயரை உள்ளிடுங்கள்',
      'use_current_location': 'தற்போதைய இடத்தைப் பயன்படுத்தவும்',
      'search': 'தேடல்',
      'cancel': 'ரத்து செய்யவும்',
    },
  };

  static String translate(String languageCode, String key) {
    return _localizedStrings[languageCode]?[key] ?? key;
  }
}
